version: '3'

services:
    nginx:
        build: ./build/nginx
        container_name:
        # not use nginx-proxy
        # ports:
        #     - "8888:80"
        networks:
            - wordpress_network
            - external_nginx_proxy
        depends_on:
            - wordpress
        volumes:
            - ./wordpress:/var/www/html
        environment:
            # use nginx-proxy
            - VIRTUAL_HOST=$VIRTUAL_HOST
            # if you use https
            - CERT_NAME=default
            # - HTTPS_METHOD=noredirect
        logging:
            options:
                max-size: "5m"
                max-file: "10"

    wordpress:
        image: wordpress:4.9.4-php7.1-fpm
        container_name:
        env_file: ./build/envfile
        networks:
            - wordpress_network
        depends_on:
            - db
        volumes:
            - ./wordpress:/var/www/html
        logging:
            options:
                max-size: "5m"
                max-file: "10"

    db:
        container_name:
        build: ./build/wordpress
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - wordpress_network
        ports:
            - "$HOST_DB_PORT:3306"
        volumes:
            - ./data:/var/lib/mysql
        logging:
            options:
                max-size: "5m"
                max-file: "10"

# volumes:
#     wordpress:
#         driver_opts:
#             type: none
#             device: ./wordpress #NOTE needs full path (~ and ./ not work)
#             o: bind

#settin virtualhost
networks:
    wordpress_network:
    #use nginx proxy
    external_nginx_proxy:
        external: true
