version: '3'

services:
    nginx:
        build: ./build
        networks:
            - wordpress_network
            - external_nginx_proxy
        depends_on:
            - wordpress
        volumes:
            - ./wordpress:/var/www/html
        environment:
            - VIRTUAL_HOST=$VIRTUAL_HOST

    wordpress:
        image: wordpress:4.9.4-php7.1-fpm
        env_file: ./build/envfile
        networks:
            - wordpress_network
        depends_on:
            - db
        volumes:
            - ./wordpress:/var/www/html

    db:
        image: mariadb:latest
        env_file: ./build/envfile
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - wordpress_network
        ports:
            - "$HOST_DB_PORT:3306"
        volumes:
            - ./data:/var/lib/mysql

# volumes:
#     wordpress:
#         driver_opts:
#             type: none
#             device: ./wordpress #NOTE needs full path (~ and ./ not work)
#             o: bind

#settin virtualhost
networks:
    wordpress_network:
    external_nginx_proxy:
        external:
            name: proxy_net
